"""currency table deleted

Revision ID: 0e2f62f831ba
Revises: 
Create Date: 2026-05-08 12:39:22.986578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e2f62f831ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('currency_code', sa.String(length=3), nullable=True))
    op.drop_column('products', 'currency_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('currency_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('products', 'currency_code')
    # ### end Alembic commands ###
