"""image column added

Revision ID: 59b81c92c716
Revises: 8f2de296fc71
Create Date: 2026-05-03 23:47:35.497967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59b81c92c716'
down_revision: Union[str, Sequence[str], None] = '8f2de296fc71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_templates', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_templates', 'image')
    # ### end Alembic commands ###
