"""id changed name uid

Revision ID: 786bf576e48b
Revises: 5057fdc74891
Create Date: 2026-04-17 15:31:04.352728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '786bf576e48b'
down_revision: Union[str, Sequence[str], None] = '5057fdc74891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uid', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=False)
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'uid')
    # ### end Alembic commands ###
