"""fix
;


Revision ID: 81d1a8e3d060
Revises: 88b6c1fb5d39
Create Date: 2026-04-24 03:09:13.360094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81d1a8e3d060'
down_revision: Union[str, Sequence[str], None] = '88b6c1fb5d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('currencies', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('update_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('currencies', 'updated_at')
    # ### end Alembic commands ###
