"""currency updated_at column added

Revision ID: 88b6c1fb5d39
Revises: d35c0354ab82
Create Date: 2026-04-24 03:03:16.159072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88b6c1fb5d39'
down_revision: Union[str, Sequence[str], None] = 'd35c0354ab82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('update_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currencies', 'update_at')
    # ### end Alembic commands ###
