"""metada changed the name with attributes

Revision ID: b8089ff8afdd
Revises: 81d1a8e3d060
Create Date: 2026-04-27 01:25:20.984745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8089ff8afdd'
down_revision: Union[str, Sequence[str], None] = '81d1a8e3d060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_templates', sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('product_templates', 'metadata_')
    op.add_column('products', sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('products', 'metadata_')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('products', 'attributes')
    op.add_column('product_templates', sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('product_templates', 'attributes')
    # ### end Alembic commands ###
